/* Blocs : texte, chemins, fichiers, messages, avancé */
(function (root) {
'use strict';
root.GA.defs.push(function (D, GA) {
  var O = GA.ORD;
  function imgOf(code) { return 'pdb.gimp_item_get_image(' + code + ')'; }
  var TL = function () { return { k: 'v', check: ['Layer'], req: true }; };
  return [
    /* ===== texte ===== */
    { type: 'txt_new', cat: 'text', msg: 'écrire %T %BR police %F taille %S px couleur %C %BR à x %X y %Y dans %IMG → dans %VAR',
      args: { T: D.ANY('Bonjour !'), F: D.STR('Sans'), S: D.NUM(24), C: D.COL('#000000'), X: D.NUM(10), Y: D.NUM(10), IMG: D.IMG(), VAR: D.VAR('calque_texte') },
      pdb: ['gimp-text-layer-new', 'gimp-image-insert-layer', 'gimp-layer-set-offsets', 'gimp-text-layer-set-color'],
      help: 'Crée un nouveau calque de texte, modifiable ensuite avec l\'outil Texte de GIMP.', kw: 'ecrire texte bulle',
      gen: function (b, c) {
        var v = c.var(b, 'VAR'), i = c.obj(b, 'IMG');
        return v + ' = pdb.gimp_text_layer_new(' + i + ', ' + c.txt(b, 'T') + ', ' + c.txt(b, 'F') + ', ' + c.num(b, 'S') + ', UNIT_PIXEL)\n' +
          'pdb.gimp_image_insert_layer(' + i + ', ' + v + ', None, 0)\n' +
          'pdb.gimp_layer_set_offsets(' + v + ', ' + c.int(b, 'X') + ', ' + c.int(b, 'Y') + ')\n' +
          'pdb.gimp_text_layer_set_color(' + v + ', ' + c.col(b, 'C') + ')\n';
      } },
    { type: 'txt_set', cat: 'text', sep: 'Modifier un calque texte', msg: 'changer le texte de %L en %T', args: { L: TL(), T: D.ANY('Nouveau texte') }, pdb: ['gimp-text-layer-set-text'],
      help: 'Remplace le texte d\'un calque texte.', gen: function (b, c) { return 'pdb.gimp_text_layer_set_text(' + c.obj(b, 'L') + ', ' + c.txt(b, 'T') + ')\n'; } },
    { type: 'txt_font', cat: 'text', msg: 'police de %L : %F', args: { L: TL(), F: D.STR('Sans') }, pdb: ['gimp-text-layer-set-font'],
      help: 'Change la police (le nom exact tel qu\'il apparaît dans GIMP).', gen: function (b, c) { return 'pdb.gimp_text_layer_set_font(' + c.obj(b, 'L') + ', ' + c.txt(b, 'F') + ')\n'; } },
    { type: 'txt_size', cat: 'text', msg: 'taille du texte de %L : %S px', args: { L: TL(), S: D.NUM(24) }, pdb: ['gimp-text-layer-set-font-size'],
      help: 'Change la taille du texte, en pixels.', tip: 'Le bloc utilise UNIT_PIXEL : la constante POINTS voudrait dire « pouces » ici !',
      gen: function (b, c) { return 'pdb.gimp_text_layer_set_font_size(' + c.obj(b, 'L') + ', ' + c.num(b, 'S') + ', UNIT_PIXEL)\n'; } },
    { type: 'txt_color', cat: 'text', msg: 'couleur du texte de %L : %C', args: { L: TL(), C: D.COL('#000000') }, pdb: ['gimp-text-layer-set-color'],
      help: 'Change la couleur du texte.', gen: function (b, c) { return 'pdb.gimp_text_layer_set_color(' + c.obj(b, 'L') + ', ' + c.col(b, 'C') + ')\n'; } },
    { type: 'txt_justify', cat: 'text', msg: 'aligner le texte de %L %J', args: { L: TL(), J: D.DD([['au centre', 'TEXT_JUSTIFY_CENTER'], ['à gauche', 'TEXT_JUSTIFY_LEFT'], ['à droite', 'TEXT_JUSTIFY_RIGHT'], ['justifié', 'TEXT_JUSTIFY_FILL']]) },
      pdb: ['gimp-text-layer-set-justification'], help: 'Aligne les lignes du texte.', kw: 'centrer', gen: function (b, c) { return 'pdb.gimp_text_layer_set_justification(' + c.obj(b, 'L') + ', ' + c.f(b, 'J') + ')\n'; } },
    { type: 'txt_spacing', cat: 'text', msg: '%K de %L : %N', args: { K: D.DD([['interligne', 'line'], ['espacement des lettres', 'letter']]), L: TL(), N: D.NUM(0) },
      pdb: ['gimp-text-layer-set-line-spacing', 'gimp-text-layer-set-letter-spacing'], help: 'Écarte ou resserre les lignes / les lettres (0 = normal, négatif = plus serré).',
      gen: function (b, c) { return 'pdb.gimp_text_layer_set_' + c.f(b, 'K') + '_spacing(' + c.obj(b, 'L') + ', ' + c.num(b, 'N') + ')\n'; } },
    { type: 'txt_box', cat: 'text', msg: 'zone de texte de %L : %W × %H', args: { L: TL(), W: D.NUM(300), H: D.NUM(100) }, pdb: ['gimp-text-layer-resize'],
      help: 'Donne une taille fixe au cadre du texte (le texte revient à la ligne dedans).', gen: function (b, c) { return 'pdb.gimp_text_layer_resize(' + c.obj(b, 'L') + ', ' + c.num(b, 'W') + ', ' + c.num(b, 'H') + ')\n'; } },
    { type: 'txt_to_path', cat: 'text', msg: 'créer un chemin à partir du texte de %L → dans %VAR', args: { L: TL(), VAR: D.VAR('chemin_texte') },
      pdb: ['gimp-vectors-new-from-text-layer', 'gimp-image-insert-vectors'], help: 'Crée le contour des lettres sous forme de chemin.',
      gen: function (b, c) { var l = c.obj(b, 'L'), v = c.var(b, 'VAR'); return v + ' = pdb.gimp_vectors_new_from_text_layer(' + imgOf(l) + ', ' + l + ')\npdb.gimp_image_insert_vectors(' + imgOf(l) + ', ' + v + ', None, 0)\n'; } },
    { type: 'txt_get', txtOut: true, cat: 'text', out: ['String'], sep: 'Lire', msg: 'texte de %L', args: { L: TL() }, pdb: ['gimp-text-layer-get-text', 'gimp-text-layer-get-markup'],
      help: 'Le texte écrit dans le calque texte.', tip: 'Quand le texte a une mise en forme (gras, couleurs…), GIMP renvoie « rien » : le bloc lit alors le balisage et retire les balises.',
      gen: function (b, c) { c.need('_texte_du_calque'); return ['_texte_du_calque(' + c.obj(b, 'L') + ')', O.CALL]; } },
    { type: 'txt_font_get', cat: 'text', out: ['String'], msg: 'police de %L', args: { L: TL() }, pdb: ['gimp-text-layer-get-font'],
      help: 'Le nom de la police du calque texte.', gen: function (b, c) { return ['pdb.gimp_text_layer_get_font(' + c.obj(b, 'L') + ')', O.CALL]; } },
    { type: 'txt_size_get', cat: 'text', out: ['Number'], msg: 'taille du texte de %L', args: { L: TL() }, pdb: ['gimp-text-layer-get-font-size'],
      help: 'La taille du texte.', gen: function (b, c) { return ['pdb.gimp_text_layer_get_font_size(' + c.obj(b, 'L') + ')[0]', O.MEMBER]; } },

    /* ===== chemins ===== */
    { type: 'path_active', cat: 'path', out: ['Vectors'], msg: 'chemin actif de %IMG', args: { IMG: D.IMG() }, pdb: ['gimp-image-get-active-vectors'],
      help: 'Le chemin sélectionné dans l\'onglet Chemins.', gen: function (b, c) { return ['pdb.gimp_image_get_active_vectors(' + c.obj(b, 'IMG') + ')', O.CALL]; } },
    { type: 'path_by_name', cat: 'path', out: ['Vectors'], msg: 'chemin nommé %N dans %IMG', args: { N: D.STR('Chemin'), IMG: D.IMG() }, pdb: ['gimp-image-get-vectors-by-name'],
      help: 'Trouve un chemin par son nom exact.', gen: function (b, c) { return ['pdb.gimp_image_get_vectors_by_name(' + c.obj(b, 'IMG') + ', ' + c.txt(b, 'N') + ')', O.CALL]; } },
    { type: 'path_new', cat: 'path', msg: 'créer un chemin vide %N dans %IMG → dans %VAR', args: { N: D.STR('Chemin'), IMG: D.IMG(), VAR: D.VAR('chemin') },
      pdb: ['gimp-vectors-new', 'gimp-image-insert-vectors'], help: 'Crée un nouveau chemin (vide) dans l\'image.',
      gen: function (b, c) { var v = c.var(b, 'VAR'), i = c.obj(b, 'IMG'); return v + ' = pdb.gimp_vectors_new(' + i + ', ' + c.txt(b, 'N') + ')\npdb.gimp_image_insert_vectors(' + i + ', ' + v + ', None, 0)\n'; } },
    { type: 'path_add', cat: 'path', msg: 'ajouter à %V un tracé passant par %L %CL fermé', args: { V: D.VEC(), L: D.LIST(), CL: D.CB(true) },
      pdb: ['gimp-vectors-stroke-new-from-points'], help: 'Dessine un tracé qui relie les points d\'une liste (chaque point = (x, y)).',
      gen: function (b, c) { c.need('_ajouter_trace'); return '_ajouter_trace(' + c.obj(b, 'V') + ', ' + c.list(b, 'L') + ', ' + (c.f(b, 'CL') === 'TRUE' ? 'True' : 'False') + ')\n'; } },
    { type: 'path_to_sel', cat: 'path', msg: 'sélectionner l\'intérieur de %V mode %OP', args: { V: D.VEC(), OP: D.DD(GA.OPT.CHANNELOP) }, pdb: ['gimp-image-select-item'],
      help: 'Transforme le chemin en sélection.', gen: function (b, c) { var v = c.obj(b, 'V'); return 'pdb.gimp_image_select_item(' + imgOf(v) + ', ' + c.f(b, 'OP') + ', ' + v + ')\n'; } },
    { type: 'path_stroke', cat: 'path', msg: 'dessiner le contour de %V sur %L', args: { V: D.VEC(), L: D.LAY() }, pdb: ['gimp-drawable-edit-stroke-item'],
      help: 'Peint le tracé du chemin avec le pinceau et la couleur de premier plan.', gen: function (b, c) { return 'pdb.gimp_drawable_edit_stroke_item(' + c.obj(b, 'L') + ', ' + c.obj(b, 'V') + ')\n'; } },
    { type: 'path_delete', cat: 'path', msg: 'supprimer le chemin %V', args: { V: D.VEC() }, pdb: ['gimp-image-remove-vectors'],
      help: 'Supprime le chemin de l\'image.', gen: function (b, c) { var v = c.obj(b, 'V'); return 'pdb.gimp_image_remove_vectors(' + imgOf(v) + ', ' + v + ')\n'; } },
    { type: 'path_points', cat: 'path', out: ['Array'], sep: 'Points', msg: 'liste des points de %V', args: { V: D.VEC() }, pdb: ['gimp-vectors-get-strokes', 'gimp-vectors-stroke-get-points'],
      help: 'Tous les points d\'ancrage du chemin, sous forme de liste de (x, y).', gen: function (b, c) { c.need('_points_du_chemin'); return ['_points_du_chemin(' + c.obj(b, 'V') + ')', O.CALL]; } },
    { type: 'path_px', cat: 'path', out: ['Number'], msg: '%K du point %P', args: { K: D.DD([['x', '0'], ['y', '1']]), P: D.OBJ() },
      help: 'La coordonnée x ou y d\'un point (venant de « liste des points » ou « pour chaque point »).', gen: function (b, c) { return [c.obj(b, 'P', O.MEMBER) + '[' + c.f(b, 'K') + ']', O.MEMBER]; } },
    { type: 'path_count', cat: 'path', out: ['Number'], msg: 'nombre de tracés dans %V', args: { V: D.VEC() }, pdb: ['gimp-vectors-get-strokes'],
      help: 'Un chemin peut contenir plusieurs tracés séparés.', gen: function (b, c) { return ['pdb.gimp_vectors_get_strokes(' + c.obj(b, 'V') + ')[0]', O.MEMBER]; } },

    /* ===== fichiers ===== */
    { type: 'file_open', cat: 'file', sep: 'Ouvrir & enregistrer', msg: 'ouvrir le fichier image %P %SHOW l\'afficher → dans %VAR', args: { P: D.STR(''), SHOW: D.CB(true), VAR: D.VAR('image_ouverte') },
      pdb: ['gimp-file-load', 'gimp-display-new'], help: 'Ouvre une image (png, jpg, xcf…).', tip: 'Le run_mode n\'est pas passé : pygimp l\'ajoute lui-même (le passer ferait planter).',
      gen: function (b, c) { var v = c.var(b, 'VAR'), p = c.txt(b, 'P'); var s = v + ' = pdb.gimp_file_load(' + p + ', ' + p + ')\n'; if (c.f(b, 'SHOW') === 'TRUE') s += 'pdb.gimp_display_new(' + v + ')\n'; return s; } },
    { type: 'file_save_next', cat: 'file', msg: 'enregistrer %IMG en .xcf à côté de son fichier', args: { IMG: D.IMG() }, pdb: ['gimp-image-get-filename', 'gimp-file-save'],
      help: 'page_01.png → page_01.xcf, dans le même dossier. Comme dans tes plug-ins.', kw: 'sauvegarder xcf',
      gen: function (b, c) { c.need('_enregistrer_xcf_a_cote'); return '_enregistrer_xcf_a_cote(' + c.obj(b, 'IMG') + ')\n'; } },
    { type: 'file_save_xcf', cat: 'file', msg: 'enregistrer %IMG en .xcf sous %P', args: { IMG: D.IMG(), P: D.STR('') }, pdb: ['gimp-file-save'],
      help: 'Enregistre au format de GIMP (garde les calques).', kw: 'sauvegarder', gen: function (b, c) { c.need('_enregistrer_xcf'); return '_enregistrer_xcf(' + c.obj(b, 'IMG') + ', ' + c.obj(b, 'P') + ')\n'; } },
    { type: 'file_png', cat: 'file', msg: 'exporter %IMG en PNG vers %P', args: { IMG: D.IMG(), P: D.STR('') },
      pdb: ['gimp-image-duplicate', 'gimp-image-merge-visible-layers', 'file-png-save-defaults', 'gimp-image-delete'],
      help: 'Exporte une copie fusionnée en PNG. L\'image d\'origine n\'est pas touchée.', gen: function (b, c) { c.need('_exporter_png'); return '_exporter_png(' + c.obj(b, 'IMG') + ', ' + c.obj(b, 'P') + ')\n'; } },
    { type: 'file_jpg', cat: 'file', msg: 'exporter %IMG en JPEG vers %P qualité %Q %', args: { IMG: D.IMG(), P: D.STR(''), Q: D.NUM(95) },
      pdb: ['gimp-image-duplicate', 'gimp-image-convert-rgb', 'gimp-image-flatten', 'file-jpeg-save', 'gimp-image-delete'],
      help: 'Exporte une copie aplatie en JPEG (qualité de 0 à 100).', gen: function (b, c) { c.need('_exporter_jpg'); return '_exporter_jpg(' + c.obj(b, 'IMG') + ', ' + c.obj(b, 'P') + ', ' + c.num(b, 'Q') + ')\n'; } },
    { type: 'file_layer_png', cat: 'file', msg: 'exporter seulement %L en PNG vers %P', args: { L: D.LAY(), P: D.STR('') }, pdb: ['file-png-save-defaults'],
      help: 'Exporte un seul calque en PNG.', gen: function (b, c) { var l = c.obj(b, 'L'), p = c.txt(b, 'P'); return 'pdb.file_png_save_defaults(' + imgOf(l) + ', ' + l + ', ' + p + ', ' + p + ')\n'; } },
    { type: 'file_read', txtOut: true, cat: 'file', out: ['String'], sep: 'Fichiers texte', msg: 'contenu du fichier texte %P', args: { P: D.STR('') },
      help: 'Lit tout un fichier texte (UTF-8, avec ou sans BOM, fins de ligne Windows gérées).', kw: 'lire txt traduction',
      gen: function (b, c) { c.need('_lire_texte'); return ['_lire_texte(' + c.obj(b, 'P') + ')', O.CALL]; } },
    { type: 'file_lines', cat: 'file', out: ['Array'], msg: 'lignes du fichier texte %P', args: { P: D.STR('') },
      help: 'Les lignes non vides d\'un fichier texte, sous forme de liste.', gen: function (b, c) { c.need('_lire_lignes'); return ['_lire_lignes(' + c.obj(b, 'P') + ')', O.CALL]; } },
    { type: 'file_write', cat: 'file', msg: 'écrire %T dans le fichier %P %MODE', args: { T: D.ANY('texte'), P: D.STR(''), MODE: D.DD([['en remplaçant son contenu', 'False'], ['à la fin', 'True']]) },
      help: 'Écrit du texte dans un fichier (UTF-8).', kw: 'sauver log', gen: function (b, c) { c.need('_ecrire_texte'); return '_ecrire_texte(' + c.obj(b, 'P') + ', ' + c.obj(b, 'T') + ', ' + c.f(b, 'MODE') + ')\n'; } },
    { type: 'file_join', txtOut: true, cat: 'file', out: ['String'], sep: 'Chemins de fichiers', msg: 'dossier %D + nom %N', args: { D: D.STR(''), N: D.STR('image.png') },
      help: 'Construit un chemin complet : dossier + nom de fichier (avec le bon séparateur \\ ou /).', gen: function (b, c) { c.need('_joindre_chemin'); return ['_joindre_chemin(' + c.obj(b, 'D') + ', ' + c.obj(b, 'N') + ')', O.CALL]; } },
    { type: 'file_part', txtOut: true, cat: 'file', out: ['String'], msg: '%K de %P', args: { K: D.DD([['dossier', '_dossier_de'], ['nom du fichier', '_nom_de_fichier'], ['chemin sans extension', '_sans_extension']]), P: D.STR('') },
      help: 'Découpe un chemin : C:\\Scans\\page.png → dossier C:\\Scans, nom page.png, sans extension C:\\Scans\\page.',
      gen: function (b, c) { var h = c.f(b, 'K'); c.need(h); return [h + '(' + c.obj(b, 'P') + ')', O.CALL]; } },
    { type: 'file_exists', cat: 'file', out: ['Boolean'], msg: 'le fichier %P existe', args: { P: D.STR('') },
      help: 'Vrai si le fichier ou dossier existe.', gen: function (b, c) { c.need('_existe'); return ['_existe(' + c.obj(b, 'P') + ')', O.CALL]; } },
    { type: 'file_list', cat: 'file', out: ['Array'], msg: 'fichiers du dossier %D se terminant par %E', args: { D: D.STR(''), E: D.STR('.png') },
      help: 'La liste triée des fichiers d\'un dossier.', gen: function (b, c) { c.need('_fichiers_du_dossier'); return ['_fichiers_du_dossier(' + c.obj(b, 'D') + ', ' + c.obj(b, 'E') + ')', O.CALL]; } },
    { type: 'file_mkdir', cat: 'file', msg: 'créer le dossier %P s\'il n\'existe pas', args: { P: D.STR('') },
      help: 'Crée un dossier (et ses dossiers parents).', gen: function (b, c) { c.need('_creer_dossier'); return '_creer_dossier(' + c.obj(b, 'P') + ')\n'; } },
    { type: 'file_plugin_dir', txtOut: true, cat: 'file', out: ['String'], msg: 'dossier de ce plug-in', args: {},
      help: 'Le dossier où se trouve ton fichier .py (pratique pour un fichier de réglages .ini à côté).',
      gen: function (b, c) { c.imp('os'); c.imp('inspect'); c.need('_texte'); return ['_texte(os.path.dirname(inspect.getfile(inspect.currentframe())))', O.CALL]; } },
    { type: 'file_gimp_dir', cat: 'file', out: ['String'], msg: 'dossier de profil de GIMP', args: {},
      help: 'Le dossier personnel de GIMP (celui qui contient plug-ins, brushes…).', gen: function () { return ['gimp.directory', O.MEMBER]; } },

    /* ===== messages ===== */
    { type: 'msg_show', cat: 'msg', msg: '💬 afficher le message %T', args: { T: D.ANY('Terminé !') }, pdb: ['gimp-message'],
      help: 'Affiche un message à l\'utilisateur (fenêtre ou console d\'erreurs selon les préférences de GIMP).', kw: 'dire alerte',
      gen: function (b, c) { return 'pdb.gimp_message(' + c.txt(b, 'T') + ')\n'; } },
    { type: 'msg_pstart', cat: 'msg', sep: 'Barre de progression', msg: 'démarrer la barre de progression %T', args: { T: D.ANY('Traitement…') },
      help: 'Affiche une barre de progression en bas de la fenêtre de GIMP.', tip: 'Utilise gimp.progress_init (pdb.gimp_progress_init demande 2 arguments).',
      gen: function (b, c) { return 'gimp.progress_init(' + c.txt(b, 'T') + ')\n'; } },
    { type: 'msg_pset', cat: 'msg', msg: 'progression à %P %', args: { P: D.NUM(50) },
      help: 'Remplit la barre (de 0 à 100).', gen: function (b, c) { return 'gimp.progress_update(' + c.num(b, 'P', O.MUL) + ' / 100.0)\n'; } },
    { type: 'msg_ptext', cat: 'msg', msg: 'texte de la progression : %T', args: { T: D.ANY('Étape 2') }, pdb: ['gimp-progress-set-text'],
      help: 'Change le texte affiché sur la barre.', gen: function (b, c) { return 'pdb.gimp_progress_set_text(' + c.txt(b, 'T') + ')\n'; } },
    { type: 'msg_ppulse', cat: 'msg', msg: 'faire bouger la barre de progression', args: {}, pdb: ['gimp-progress-pulse'],
      help: 'Montre que ça travaille, sans pourcentage.', gen: function () { return 'pdb.gimp_progress_pulse()\n'; } },
    { type: 'msg_pend', cat: 'msg', msg: 'terminer la barre de progression', args: {}, pdb: ['gimp-progress-end'],
      help: 'Retire la barre de progression.', gen: function () { return 'pdb.gimp_progress_end()\n'; } },
    { type: 'msg_flush', cat: 'msg', sep: 'Affichage', msg: 'rafraîchir l\'affichage', args: {},
      help: 'Met à jour les fenêtres d\'image tout de suite (fait aussi automatiquement à la fin).', gen: function () { return 'gimp.displays_flush()\n'; } },
    { type: 'msg_version', cat: 'msg', out: ['String'], msg: 'version de GIMP', args: {}, pdb: ['gimp-version'],
      help: 'Ex. « 2.10.34 ».', gen: function () { return ['pdb.gimp_version()', O.CALL]; } },

    /* ===== avancé ===== */
    { type: 'adv_py_line', cat: 'adv', sep: 'Code Python libre', msg: '🐍 ligne Python : %CODE', args: { CODE: D.TXT('pass') },
      help: 'Une ligne de Python 2 écrite à la main (utilise les noms de variables de l\'onglet Code).', tip: 'Pour les imports dont tu as besoin : ⚙️ Mon plug-in ▸ Imports.',
      gen: function (b) { return String(b.getFieldValue('CODE') || 'pass').replace(/[\r\n]+/g, ' ') + '\n'; } },
    { type: 'adv_py_expr', cat: 'adv', out: null, msg: '🐍 valeur Python : %CODE', args: { CODE: D.TXT('image.width') },
      help: 'Une expression Python 2 qui donne une valeur.', gen: function (b) { return [String(b.getFieldValue('CODE') || 'None').replace(/[\r\n]+/g, ' '), O.NONE]; } },
    { type: 'adv_id_layer', cat: 'adv', out: ['Layer'], sep: 'Numéros (ID) renvoyés par GIMP', msg: 'calque dont l\'ID est %N', args: { N: D.NUM(0) },
      help: 'Certaines fonctions renvoient des numéros (entiers) au lieu de calques : ce bloc retrouve le calque.', gen: function (b, c) { return ['gimp._id2drawable(' + c.int(b, 'N') + ')', O.CALL]; } },
    { type: 'adv_id_path', cat: 'adv', out: ['Vectors'], msg: 'chemin dont l\'ID est %N', args: { N: D.NUM(0) },
      help: 'Retrouve un chemin à partir de son numéro (ID entier).', gen: function (b, c) { return ['gimp._id2vectors(' + c.int(b, 'N') + ')', O.CALL]; } }
  ];
});
})(typeof window !== 'undefined' ? window : globalThis);
