/* Blocs : image, calques, sélection, peinture */
(function (root) {
'use strict';
root.GA.defs.push(function (D, GA) {
  var O = GA.ORD;
  function img(c, b, n) { return c.obj(b, n || 'IMG'); }
  function imgOf(c, code) { return 'pdb.gimp_item_get_image(' + code + ')'; }
  var OP = GA.OPT;
  return [
    /* ===== image ===== */
    { type: 'g_cur_image', cat: 'image', out: ['Image'], msg: '🖼️ image actuelle', args: {},
      help: 'L\'image sur laquelle l\'utilisateur a lancé le plug-in.', gen: function () { return ['image', O.ATOMIC]; } },
    { type: 'img_width', cat: 'image', out: ['Number'], msg: 'largeur de %IMG', args: { IMG: D.IMG() }, pdb: ['gimp-image-width'],
      help: 'La largeur de l\'image, en pixels.', gen: function (b, c) { return ['pdb.gimp_image_width(' + img(c, b) + ')', O.CALL]; } },
    { type: 'img_height', cat: 'image', out: ['Number'], msg: 'hauteur de %IMG', args: { IMG: D.IMG() }, pdb: ['gimp-image-height'],
      help: 'La hauteur de l\'image, en pixels.', gen: function (b, c) { return ['pdb.gimp_image_height(' + img(c, b) + ')', O.CALL]; } },
    { type: 'img_name', cat: 'image', out: ['String'], msg: 'nom de %IMG', args: { IMG: D.IMG() }, pdb: ['gimp-image-get-name'],
      help: 'Le nom affiché de l\'image (ex. page_01.png).', gen: function (b, c) { return ['pdb.gimp_image_get_name(' + img(c, b) + ')', O.CALL]; } },
    { type: 'img_file', txtOut: true, cat: 'image', out: ['String'], msg: 'chemin du fichier de %IMG', args: { IMG: D.IMG() }, pdb: ['gimp-image-get-filename'],
      help: 'Le chemin complet du fichier de l\'image. Vide si l\'image n\'a jamais été enregistrée.',
      gen: function (b, c) { c.need('_texte'); return ['_texte(pdb.gimp_image_get_filename(' + img(c, b) + '))', O.CALL]; } },
    { type: 'img_has_file', cat: 'image', out: ['Boolean'], msg: '%IMG a un fichier', args: { IMG: D.IMG() }, pdb: ['gimp-image-get-filename'],
      help: 'Vrai si l\'image vient d\'un fichier (ou a déjà été enregistrée).',
      gen: function (b, c) { return ['(pdb.gimp_image_get_filename(' + img(c, b) + ') is not None)', O.ATOMIC]; } },
    { type: 'img_active_layer', cat: 'image', out: ['Layer'], msg: 'calque actif de %IMG', args: { IMG: D.IMG() }, pdb: ['gimp-image-get-active-layer'],
      help: 'Le calque sélectionné en ce moment dans l\'image.', gen: function (b, c) { return ['pdb.gimp_image_get_active_layer(' + img(c, b) + ')', O.CALL]; } },
    { type: 'img_layer_by_name', cat: 'image', out: ['Layer'], msg: 'calque nommé %NAME dans %IMG', args: { NAME: D.STR('text #1'), IMG: D.IMG() }, pdb: ['gimp-image-get-layer-by-name'],
      help: 'Trouve un calque par son nom exact (même dans les groupes). Vérifie avec « … existe » : s\'il n\'existe pas, le résultat est vide.', kw: 'chercher trouver',
      gen: function (b, c) { return ['pdb.gimp_image_get_layer_by_name(' + img(c, b) + ', ' + c.txt(b, 'NAME') + ')', O.CALL]; } },
    { type: 'img_layer_count', cat: 'image', out: ['Number'], msg: 'nombre de calques de %IMG', args: { IMG: D.IMG() }, pdb: ['gimp-image-get-layers'],
      help: 'Combien de calques il y a au premier niveau (les groupes comptent pour 1).', gen: function (b, c) { return ['pdb.gimp_image_get_layers(' + img(c, b) + ')[0]', O.MEMBER]; } },
    { type: 'img_new', cat: 'image', sep: 'Créer & transformer', msg: 'créer une image %W × %H fond %FILL %BR %SHOW l\'afficher → dans %VAR',
      args: { W: D.NUM(1000), H: D.NUM(1500), FILL: D.DD([['blanc', 'FILL_WHITE'], ['transparent', 'FILL_TRANSPARENT'], ['premier plan', 'FILL_FOREGROUND'], ['arrière-plan', 'FILL_BACKGROUND']]), SHOW: D.CB(true), VAR: D.VAR('nouvelle_image') },
      pdb: ['gimp-image-new', 'gimp-layer-new', 'gimp-image-insert-layer', 'gimp-drawable-fill', 'gimp-display-new'],
      help: 'Crée une nouvelle image avec un calque de fond, et la range dans une variable.',
      gen: function (b, c) {
        var v = c.var(b, 'VAR'), f = c.uid('fond'), w = c.int(b, 'W'), h = c.int(b, 'H');
        var s = v + ' = pdb.gimp_image_new(' + w + ', ' + h + ', RGB)\n' +
          f + ' = pdb.gimp_layer_new(' + v + ', ' + w + ', ' + h + ', RGBA_IMAGE, "Arrière-plan", 100, NORMAL_MODE)\n' +
          'pdb.gimp_image_insert_layer(' + v + ', ' + f + ', None, 0)\n' +
          'pdb.gimp_drawable_fill(' + f + ', ' + c.f(b, 'FILL') + ')\n';
        if (c.f(b, 'SHOW') === 'TRUE') s += 'pdb.gimp_display_new(' + v + ')\n';
        return s;
      } },
    { type: 'img_duplicate', cat: 'image', msg: 'dupliquer %IMG → dans %VAR', args: { IMG: D.IMG(), VAR: D.VAR('copie') }, pdb: ['gimp-image-duplicate'],
      help: 'Fait une copie complète de l\'image (invisible tant que tu ne l\'affiches pas).', gen: function (b, c) { return c.var(b, 'VAR') + ' = pdb.gimp_image_duplicate(' + img(c, b) + ')\n'; } },
    { type: 'img_show', cat: 'image', msg: 'afficher %IMG dans une fenêtre', args: { IMG: D.IMG() }, pdb: ['gimp-display-new'],
      help: 'Ouvre une fenêtre pour voir l\'image.', gen: function (b, c) { return 'pdb.gimp_display_new(' + img(c, b) + ')\n'; } },
    { type: 'img_delete', cat: 'image', msg: 'oublier %IMG (image sans fenêtre)', args: { IMG: D.IMG() }, pdb: ['gimp-image-delete'],
      help: 'Libère la mémoire d\'une image de travail invisible (copie, image ouverte en arrière-plan).', tip: 'Ne marche pas sur une image affichée dans une fenêtre.',
      gen: function (b, c) { return 'pdb.gimp_image_delete(' + img(c, b) + ')\n'; } },
    { type: 'img_flatten', cat: 'image', msg: 'aplatir %IMG', args: { IMG: D.IMG() }, pdb: ['gimp-image-flatten'],
      help: 'Fusionne tous les calques en un seul (et retire la transparence).', gen: function (b, c) { return 'pdb.gimp_image_flatten(' + img(c, b) + ')\n'; } },
    { type: 'img_merge', cat: 'image', msg: 'fusionner les calques visibles de %IMG → dans %VAR', args: { IMG: D.IMG(), VAR: D.VAR('calque_fusionne') }, pdb: ['gimp-image-merge-visible-layers'],
      help: 'Fusionne les calques visibles en un seul calque.', gen: function (b, c) { return c.var(b, 'VAR') + ' = pdb.gimp_image_merge_visible_layers(' + img(c, b) + ', CLIP_TO_IMAGE)\n'; } },
    { type: 'img_scale', cat: 'image', msg: 'redimensionner %IMG à %W × %H', args: { IMG: D.IMG(), W: D.NUM(1000), H: D.NUM(1500) }, pdb: ['gimp-image-scale'],
      help: 'Change la taille de toute l\'image (le contenu est étiré).', kw: 'taille echelle', gen: function (b, c) { return 'pdb.gimp_image_scale(' + img(c, b) + ', ' + c.int(b, 'W') + ', ' + c.int(b, 'H') + ')\n'; } },
    { type: 'img_canvas', cat: 'image', msg: 'taille du canevas de %IMG : %W × %H %BR décalage x %X y %Y', args: { IMG: D.IMG(), W: D.NUM(1200), H: D.NUM(1800), X: D.NUM(0), Y: D.NUM(0) }, pdb: ['gimp-image-resize'],
      help: 'Agrandit ou réduit la « feuille » sans étirer le contenu.', gen: function (b, c) { return 'pdb.gimp_image_resize(' + img(c, b) + ', ' + c.int(b, 'W') + ', ' + c.int(b, 'H') + ', ' + c.int(b, 'X') + ', ' + c.int(b, 'Y') + ')\n'; } },
    { type: 'img_crop', cat: 'image', msg: 'recadrer %IMG : largeur %W hauteur %H %BR depuis x %X y %Y', args: { IMG: D.IMG(), W: D.NUM(500), H: D.NUM(500), X: D.NUM(0), Y: D.NUM(0) }, pdb: ['gimp-image-crop'],
      help: 'Garde seulement le rectangle indiqué.', gen: function (b, c) { return 'pdb.gimp_image_crop(' + img(c, b) + ', ' + c.int(b, 'W') + ', ' + c.int(b, 'H') + ', ' + c.int(b, 'X') + ', ' + c.int(b, 'Y') + ')\n'; } },
    { type: 'img_fit', cat: 'image', msg: 'ajuster le canevas de %IMG à ses calques', args: { IMG: D.IMG() }, pdb: ['gimp-image-resize-to-layers'],
      help: 'Agrandit la feuille pour que tous les calques soient visibles.', gen: function (b, c) { return 'pdb.gimp_image_resize_to_layers(' + img(c, b) + ')\n'; } },
    { type: 'img_rotate', cat: 'image', msg: 'pivoter %IMG de %R', args: { IMG: D.IMG(), R: D.DD([['90° (horaire)', 'ROTATE_90'], ['180°', 'ROTATE_180'], ['270° (anti-horaire)', 'ROTATE_270']]) }, pdb: ['gimp-image-rotate'],
      help: 'Fait tourner toute l\'image.', gen: function (b, c) { return 'pdb.gimp_image_rotate(' + img(c, b) + ', ' + c.f(b, 'R') + ')\n'; } },
    { type: 'img_flip', cat: 'image', msg: 'retourner %IMG %O', args: { IMG: D.IMG(), O: D.DD([['horizontalement (miroir)', 'ORIENTATION_HORIZONTAL'], ['verticalement', 'ORIENTATION_VERTICAL']]) }, pdb: ['gimp-image-flip'],
      help: 'Retourne toute l\'image comme dans un miroir.', gen: function (b, c) { return 'pdb.gimp_image_flip(' + img(c, b) + ', ' + c.f(b, 'O') + ')\n'; } },
    { type: 'img_mode', cat: 'image', msg: 'passer %IMG en %M', args: { IMG: D.IMG(), M: D.DD([['couleurs (RGB)', 'RGB'], ['niveaux de gris', 'GRAY']]) }, pdb: ['gimp-image-base-type', 'gimp-image-convert-rgb', 'gimp-image-convert-grayscale'],
      help: 'Change le mode de l\'image. Ne fait rien si elle y est déjà (sinon GIMP afficherait une erreur).',
      gen: function (b, c) { var m = c.f(b, 'M'), i = img(c, b); return 'if pdb.gimp_image_base_type(' + i + ') != ' + m + ':\n' + GA.G.INDENT + 'pdb.gimp_image_convert_' + (m === 'RGB' ? 'rgb' : 'grayscale') + '(' + i + ')\n'; } },
    { type: 'img_guide', cat: 'image', msg: 'ajouter un guide %O à %P px dans %IMG', args: { O: D.DD([['vertical', 'v'], ['horizontal', 'h']]), P: D.NUM(100), IMG: D.IMG() }, pdb: ['gimp-image-add-vguide', 'gimp-image-add-hguide'],
      help: 'Ajoute une ligne-guide bleue (non imprimée).', gen: function (b, c) { return 'pdb.gimp_image_add_' + c.f(b, 'O') + 'guide(' + img(c, b) + ', ' + c.int(b, 'P') + ')\n'; } },

    /* ===== calques ===== */
    { type: 'g_cur_drawable', cat: 'layer', out: ['Layer'], msg: '📑 calque actif au lancement', args: {},
      help: 'Le calque qui était sélectionné quand l\'utilisateur a lancé le plug-in.', gen: function () { return ['drawable', O.ATOMIC]; } },
    { type: 'lyr_new', cat: 'layer', sep: 'Créer & supprimer', msg: 'créer un calque %NAME %BR taille %W × %H rempli %FILL %BR dans %IMG placé %POS → dans %VAR',
      args: { NAME: D.STR('Nouveau calque'), W: D.W(), H: D.H(), FILL: D.DD(OP.FILL), IMG: D.IMG(), POS: D.DD([['tout en haut', 'TOP'], ['au-dessus du calque actif', 'ACTIVE'], ['tout en bas', 'BOTTOM']]), VAR: D.VAR('calque') },
      pdb: ['gimp-layer-new', 'gimp-image-insert-layer', 'gimp-drawable-fill'],
      help: 'Crée un calque, l\'ajoute à l\'image et le range dans une variable pour la suite.', kw: 'nouveau calque ajouter',
      gen: function (b, c) {
        var v = c.var(b, 'VAR'), i = img(c, b), pos = { TOP: '0', ACTIVE: '-1', BOTTOM: 'len(' + i + '.layers)' }[c.f(b, 'POS')];
        return v + ' = pdb.gimp_layer_new(' + i + ', ' + c.int(b, 'W') + ', ' + c.int(b, 'H') + ', RGBA_IMAGE, ' + c.txt(b, 'NAME') + ', 100, NORMAL_MODE)\n' +
          'pdb.gimp_image_insert_layer(' + i + ', ' + v + ', None, ' + pos + ')\n' +
          'pdb.gimp_drawable_fill(' + v + ', ' + c.f(b, 'FILL') + ')\n';
      } },
    { type: 'lyr_group', cat: 'layer', msg: 'créer un groupe de calques %NAME dans %IMG → dans %VAR', args: { NAME: D.STR('Groupe'), IMG: D.IMG(), VAR: D.VAR('groupe') },
      pdb: ['gimp-layer-group-new', 'gimp-item-set-name', 'gimp-image-insert-layer'], help: 'Crée un dossier de calques (groupe).',
      gen: function (b, c) { var v = c.var(b, 'VAR'), i = img(c, b); return v + ' = pdb.gimp_layer_group_new(' + i + ')\npdb.gimp_item_set_name(' + v + ', ' + c.txt(b, 'NAME') + ')\npdb.gimp_image_insert_layer(' + i + ', ' + v + ', None, 0)\n'; } },
    { type: 'lyr_dup', cat: 'layer', msg: 'dupliquer %L → dans %VAR', args: { L: D.LAY(), VAR: D.VAR('copie_calque') },
      pdb: ['gimp-layer-copy', 'gimp-item-get-image', 'gimp-item-get-parent', 'gimp-image-get-item-position', 'gimp-image-insert-layer'],
      help: 'Copie le calque juste au-dessus de l\'original, dans le même groupe.',
      gen: function (b, c) {
        var v = c.var(b, 'VAR'), l = c.obj(b, 'L'), im = c.uid('img');
        return im + ' = ' + imgOf(c, l) + '\n' + v + ' = pdb.gimp_layer_copy(' + l + ', True)\n' +
          'pdb.gimp_image_insert_layer(' + im + ', ' + v + ', pdb.gimp_item_get_parent(' + l + '), pdb.gimp_image_get_item_position(' + im + ', ' + l + '))\n';
      } },
    { type: 'lyr_delete', cat: 'layer', msg: 'supprimer %L', args: { L: D.LAY() }, pdb: ['gimp-image-remove-layer'],
      help: 'Supprime le calque (ou le groupe) de l\'image.', gen: function (b, c) { var l = c.obj(b, 'L'); return 'pdb.gimp_image_remove_layer(' + imgOf(c, l) + ', ' + l + ')\n'; } },
    { type: 'lyr_import', cat: 'layer', msg: 'importer le fichier %P comme calque dans %IMG → dans %VAR', args: { P: D.STR(''), IMG: D.IMG(), VAR: D.VAR('calque_importe') },
      pdb: ['gimp-file-load-layer', 'gimp-image-insert-layer'], help: 'Ouvre une image et l\'ajoute comme nouveau calque en haut de la pile.', kw: 'ouvrir comme calque',
      gen: function (b, c) { var v = c.var(b, 'VAR'), i = img(c, b); return v + ' = pdb.gimp_file_load_layer(' + i + ', ' + c.txt(b, 'P') + ')\npdb.gimp_image_insert_layer(' + i + ', ' + v + ', None, 0)\n'; } },
    { type: 'lyr_rename', cat: 'layer', sep: 'Nom, visibilité, ordre', msg: 'renommer %L en %NAME', args: { L: D.ITEM(), NAME: D.STR('Nouveau nom') }, pdb: ['gimp-item-set-name'],
      help: 'Change le nom d\'un calque, d\'un groupe ou d\'un chemin.', gen: function (b, c) { return 'pdb.gimp_item_set_name(' + c.obj(b, 'L') + ', ' + c.txt(b, 'NAME') + ')\n'; } },
    { type: 'lyr_name', cat: 'layer', out: ['String'], msg: 'nom de %L', args: { L: D.ITEM() }, pdb: ['gimp-item-get-name'],
      help: 'Le nom du calque (ou du chemin).', gen: function (b, c) { return ['pdb.gimp_item_get_name(' + c.obj(b, 'L') + ')', O.CALL]; } },
    { type: 'lyr_visible', cat: 'layer', msg: 'visibilité de %L : %V', args: { L: D.ITEM(), V: D.BOOLS(true) }, pdb: ['gimp-item-set-visible'],
      help: 'Affiche (vrai) ou cache (faux) le calque — l\'œil dans la liste des calques.', kw: 'afficher masquer cacher oeil',
      gen: function (b, c) { return 'pdb.gimp_item_set_visible(' + c.obj(b, 'L') + ', ' + c.bool(b, 'V') + ')\n'; } },
    { type: 'lyr_is_visible', cat: 'layer', out: ['Boolean'], msg: '%L est visible', args: { L: D.ITEM() }, pdb: ['gimp-item-get-visible'],
      help: 'Vrai si l\'œil du calque est ouvert.', gen: function (b, c) { return ['pdb.gimp_item_get_visible(' + c.obj(b, 'L') + ')', O.CALL]; } },
    { type: 'lyr_order', cat: 'layer', msg: '%OP %L', args: { OP: D.DD([['monter tout en haut', 'raise_item_to_top'], ['descendre tout en bas', 'lower_item_to_bottom'], ['monter d\'un cran', 'raise_item'], ['descendre d\'un cran', 'lower_item']]), L: D.ITEM() },
      pdb: ['gimp-image-raise-item-to-top', 'gimp-image-lower-item-to-bottom', 'gimp-image-raise-item', 'gimp-image-lower-item'],
      help: 'Déplace le calque dans la pile (dans son groupe).', gen: function (b, c) { var l = c.obj(b, 'L'); return 'pdb.gimp_image_' + c.f(b, 'OP') + '(' + imgOf(c, l) + ', ' + l + ')\n'; } },
    { type: 'lyr_to_group', cat: 'layer', msg: 'mettre %L dans le groupe %G', args: { L: D.LAY(), G: D.GRP() }, pdb: ['gimp-image-reorder-item'],
      help: 'Range le calque en haut d\'un groupe de calques.', gen: function (b, c) { var l = c.obj(b, 'L'); return 'pdb.gimp_image_reorder_item(' + imgOf(c, l) + ', ' + l + ', ' + c.obj(b, 'G') + ', 0)\n'; } },
    { type: 'lyr_activate', cat: 'layer', msg: 'sélectionner %L dans la liste des calques', args: { L: D.LAY() }, pdb: ['gimp-image-set-active-layer'],
      help: 'Rend ce calque actif (surligné dans la liste).', gen: function (b, c) { var l = c.obj(b, 'L'); return 'pdb.gimp_image_set_active_layer(' + imgOf(c, l) + ', ' + l + ')\n'; } },
    { type: 'lyr_opacity', cat: 'layer', sep: 'Apparence & position', msg: 'opacité de %L : %O %', args: { L: D.LAY(), O: D.NUM(100) }, pdb: ['gimp-layer-set-opacity'],
      help: 'De 0 (invisible) à 100 (opaque).', gen: function (b, c) { return 'pdb.gimp_layer_set_opacity(' + c.obj(b, 'L') + ', ' + c.num(b, 'O') + ')\n'; } },
    { type: 'lyr_mode', cat: 'layer', msg: 'mode de fusion de %L : %M', args: { L: D.LAY(), M: D.DD(OP.MODE) }, pdb: ['gimp-layer-set-mode'],
      help: 'Comment le calque se mélange avec ceux du dessous.', gen: function (b, c) { return 'pdb.gimp_layer_set_mode(' + c.obj(b, 'L') + ', ' + c.f(b, 'M') + ')\n'; } },
    { type: 'lyr_place', cat: 'layer', msg: 'placer %L à x %X y %Y', args: { L: D.LAY(), X: D.NUM(0), Y: D.NUM(0) }, pdb: ['gimp-layer-set-offsets'],
      help: 'Place le coin en haut à gauche du calque à cette position.', kw: 'position deplacer', gen: function (b, c) { return 'pdb.gimp_layer_set_offsets(' + c.obj(b, 'L') + ', ' + c.int(b, 'X') + ', ' + c.int(b, 'Y') + ')\n'; } },
    { type: 'lyr_move', cat: 'layer', msg: 'déplacer %L de x %X y %Y', args: { L: D.ITEM(), X: D.NUM(10), Y: D.NUM(0) }, pdb: ['gimp-item-transform-translate'],
      help: 'Décale le calque (ou le chemin) de ce nombre de pixels.', gen: function (b, c) { return 'pdb.gimp_item_transform_translate(' + c.obj(b, 'L') + ', ' + c.num(b, 'X') + ', ' + c.num(b, 'Y') + ')\n'; } },
    { type: 'lyr_measure', cat: 'layer', out: ['Number'], msg: '%K de %L', args: { K: D.DD([['position x', 'X'], ['position y', 'Y'], ['largeur', 'W'], ['hauteur', 'H']]), L: D.LAY() },
      pdb: ['gimp-drawable-offsets', 'gimp-drawable-width', 'gimp-drawable-height'], help: 'La position ou la taille du calque, en pixels.',
      gen: function (b, c) { var l = c.obj(b, 'L'), k = c.f(b, 'K'); if (k === 'X' || k === 'Y') return ['pdb.gimp_drawable_offsets(' + l + ')[' + (k === 'X' ? 0 : 1) + ']', O.MEMBER]; return ['pdb.gimp_drawable_' + (k === 'W' ? 'width' : 'height') + '(' + l + ')', O.CALL]; } },
    { type: 'lyr_scale', cat: 'layer', msg: 'redimensionner %L à %W × %H', args: { L: D.LAY(), W: D.NUM(200), H: D.NUM(200) }, pdb: ['gimp-layer-scale'],
      help: 'Étire le calque à la nouvelle taille.', gen: function (b, c) { return 'pdb.gimp_layer_scale(' + c.obj(b, 'L') + ', ' + c.int(b, 'W') + ', ' + c.int(b, 'H') + ', True)\n'; } },
    { type: 'lyr_fit', cat: 'layer', msg: 'ajuster %L à la taille de l\'image', args: { L: D.LAY() }, pdb: ['gimp-layer-resize-to-image-size'],
      help: 'Donne au calque exactement la taille de l\'image (sans étirer).', gen: function (b, c) { return 'pdb.gimp_layer_resize_to_image_size(' + c.obj(b, 'L') + ')\n'; } },
    { type: 'lyr_alpha', cat: 'layer', msg: 'ajouter la transparence à %L', args: { L: D.LAY() }, pdb: ['gimp-layer-add-alpha'],
      help: 'Ajoute un canal alpha pour que l\'effacement donne du transparent.', gen: function (b, c) { return 'pdb.gimp_layer_add_alpha(' + c.obj(b, 'L') + ')\n'; } },
    { type: 'lyr_merge_down', cat: 'layer', msg: 'fusionner %L avec celui du dessous → dans %VAR', args: { L: D.LAY(), VAR: D.VAR('calque_fusionne') }, pdb: ['gimp-image-merge-down'],
      help: 'Fusionne le calque avec le calque juste en dessous.', gen: function (b, c) { var l = c.obj(b, 'L'); return c.var(b, 'VAR') + ' = pdb.gimp_image_merge_down(' + imgOf(c, l) + ', ' + l + ', EXPAND_AS_NECESSARY)\n'; } },
    { type: 'lyr_mask', cat: 'layer', msg: 'ajouter un masque %T à %L', args: { T: D.DD([['blanc (tout visible)', 'ADD_MASK_WHITE'], ['noir (tout caché)', 'ADD_MASK_BLACK'], ['depuis la sélection', 'ADD_MASK_SELECTION'], ['depuis la transparence', 'ADD_MASK_ALPHA']]), L: D.LAY() },
      pdb: ['gimp-layer-create-mask', 'gimp-layer-add-mask'], help: 'Ajoute un masque de calque.',
      gen: function (b, c) { var l = c.obj(b, 'L'), m = c.uid('masque'); return m + ' = pdb.gimp_layer_create_mask(' + l + ', ' + c.f(b, 'T') + ')\npdb.gimp_layer_add_mask(' + l + ', ' + m + ')\n'; } },
    { type: 'lyr_mask_end', cat: 'layer', msg: '%OP le masque de %L', args: { OP: D.DD([['appliquer', 'MASK_APPLY'], ['supprimer', 'MASK_DISCARD']]), L: D.LAY() },
      pdb: ['gimp-layer-get-mask', 'gimp-layer-remove-mask'], help: 'Applique ou jette le masque du calque (s\'il en a un).',
      gen: function (b, c) { var l = c.obj(b, 'L'); return 'if pdb.gimp_layer_get_mask(' + l + ') is not None:\n' + GA.G.INDENT + 'pdb.gimp_layer_remove_mask(' + l + ', ' + c.f(b, 'OP') + ')\n'; } },
    { type: 'lyr_is_group', cat: 'layer', out: ['Boolean'], sep: 'Questions', msg: '%L est un groupe', args: { L: D.ITEM() }, pdb: ['gimp-item-is-group'],
      help: 'Vrai si c\'est un groupe (dossier) de calques.', gen: function (b, c) { return ['pdb.gimp_item_is_group(' + c.obj(b, 'L') + ')', O.CALL]; } },
    { type: 'lyr_is_text', cat: 'layer', out: ['Boolean'], msg: '%L est un calque texte', args: { L: D.ITEM() }, pdb: ['gimp-item-is-text-layer'],
      help: 'Vrai si c\'est un calque de texte (avec le « T » dans la liste).', gen: function (b, c) { return ['pdb.gimp_item_is_text_layer(' + c.obj(b, 'L') + ')', O.CALL]; } },
    { type: 'lyr_parent', cat: 'layer', out: ['Layer'], msg: 'groupe qui contient %L', args: { L: D.ITEM() }, pdb: ['gimp-item-get-parent'],
      help: 'Le groupe dans lequel se trouve le calque (vide s\'il est à la racine).', gen: function (b, c) { return ['pdb.gimp_item_get_parent(' + c.obj(b, 'L') + ')', O.CALL]; } },
    { type: 'lyr_list', cat: 'layer', out: ['Array'], msg: 'liste des calques de %IMG %BR %REC chercher aussi dans les groupes', args: { IMG: D.IMGL(), REC: D.CB(true) },
      help: 'Tous les calques (sans les groupes), sous forme de liste.', gen: function (b, c) { c.need('_liste_calques'); return ['_liste_calques(' + c.obj(b, 'IMG') + ', ' + (c.f(b, 'REC') === 'TRUE' ? 'True' : 'False') + ', False)', O.CALL]; } },

    /* ===== sélection ===== */
    { type: 'sel_all', cat: 'sel', msg: 'tout sélectionner dans %IMG', args: { IMG: D.IMG() }, pdb: ['gimp-selection-all'],
      help: 'Sélectionne toute l\'image (Ctrl+A).', gen: function (b, c) { return 'pdb.gimp_selection_all(' + img(c, b) + ')\n'; } },
    { type: 'sel_none', cat: 'sel', msg: 'tout désélectionner dans %IMG', args: { IMG: D.IMG() }, pdb: ['gimp-selection-none'],
      help: 'Enlève la sélection (Maj+Ctrl+A).', gen: function (b, c) { return 'pdb.gimp_selection_none(' + img(c, b) + ')\n'; } },
    { type: 'sel_invert', cat: 'sel', msg: 'inverser la sélection de %IMG', args: { IMG: D.IMG() }, pdb: ['gimp-selection-invert'],
      help: 'Ce qui était sélectionné ne l\'est plus, et inversement (Ctrl+I).', gen: function (b, c) { return 'pdb.gimp_selection_invert(' + img(c, b) + ')\n'; } },
    { type: 'sel_rect', cat: 'sel', msg: 'sélectionner un rectangle x %X y %Y largeur %W hauteur %H %BR mode %OP dans %IMG',
      args: { X: D.NUM(0), Y: D.NUM(0), W: D.NUM(200), H: D.NUM(100), OP: D.DD(OP.CHANNELOP), IMG: D.IMG() }, pdb: ['gimp-image-select-rectangle'],
      help: 'Sélection rectangulaire. « ajouter » garde l\'ancienne sélection en plus.', gen: function (b, c) { return 'pdb.gimp_image_select_rectangle(' + img(c, b) + ', ' + c.f(b, 'OP') + ', ' + c.num(b, 'X') + ', ' + c.num(b, 'Y') + ', ' + c.num(b, 'W') + ', ' + c.num(b, 'H') + ')\n'; } },
    { type: 'sel_ellipse', cat: 'sel', msg: 'sélectionner une ellipse x %X y %Y largeur %W hauteur %H %BR mode %OP dans %IMG',
      args: { X: D.NUM(0), Y: D.NUM(0), W: D.NUM(200), H: D.NUM(100), OP: D.DD(OP.CHANNELOP), IMG: D.IMG() }, pdb: ['gimp-image-select-ellipse'],
      help: 'Sélection ovale (ou ronde si largeur = hauteur).', gen: function (b, c) { return 'pdb.gimp_image_select_ellipse(' + img(c, b) + ', ' + c.f(b, 'OP') + ', ' + c.num(b, 'X') + ', ' + c.num(b, 'Y') + ', ' + c.num(b, 'W') + ', ' + c.num(b, 'H') + ')\n'; } },
    { type: 'sel_item', cat: 'sel', msg: 'sélectionner la forme de %IT mode %OP', args: { IT: D.ITEM(), OP: D.DD(OP.CHANNELOP) }, pdb: ['gimp-image-select-item'],
      help: 'Sélectionne le contenu non transparent d\'un calque, l\'intérieur d\'un chemin ou un canal enregistré.', kw: 'alpha vers selection chemin vers selection',
      gen: function (b, c) { var it = c.obj(b, 'IT'); return 'pdb.gimp_image_select_item(' + imgOf(c, it) + ', ' + c.f(b, 'OP') + ', ' + it + ')\n'; } },
    { type: 'sel_color', cat: 'sel', msg: 'sélectionner la couleur %C dans %L mode %OP', args: { C: D.COL('#ffffff'), L: D.LAY(), OP: D.DD(OP.CHANNELOP) }, pdb: ['gimp-image-select-color'],
      help: 'Sélectionne tous les pixels de cette couleur.', kw: 'baguette',
      gen: function (b, c) { var l = c.obj(b, 'L'); return 'pdb.gimp_image_select_color(' + imgOf(c, l) + ', ' + c.f(b, 'OP') + ', ' + l + ', ' + c.col(b, 'C') + ')\n'; } },
    { type: 'sel_modify', cat: 'sel', sep: 'Modifier', msg: '%OP la sélection de %IMG de %N px', args: { OP: D.DD([['agrandir', 'grow'], ['réduire', 'shrink'], ['adoucir (flou du bord)', 'feather'], ['transformer en bordure', 'border']]), IMG: D.IMG(), N: D.NUM(5) },
      pdb: ['gimp-selection-grow', 'gimp-selection-shrink', 'gimp-selection-feather', 'gimp-selection-border'], help: 'Modifie la forme de la sélection.',
      gen: function (b, c) { return 'pdb.gimp_selection_' + c.f(b, 'OP') + '(' + img(c, b) + ', ' + c.num(b, 'N') + ')\n'; } },
    { type: 'sel_flood', cat: 'sel', msg: 'boucher les trous de la sélection de %IMG', args: { IMG: D.IMG() }, pdb: ['gimp-selection-flood'],
      help: 'Remplit les trous à l\'intérieur de la sélection (ex. le texte dans une bulle).', kw: 'bulle remplir trous',
      gen: function (b, c) { return 'pdb.gimp_selection_flood(' + img(c, b) + ')\n'; } },
    { type: 'sel_sharpen', cat: 'sel', msg: 'rendre nette la sélection de %IMG', args: { IMG: D.IMG() }, pdb: ['gimp-selection-sharpen'],
      help: 'Retire l\'adoucissement des bords.', gen: function (b, c) { return 'pdb.gimp_selection_sharpen(' + img(c, b) + ')\n'; } },
    { type: 'sel_save', cat: 'sel', msg: 'mémoriser la sélection de %IMG → dans %VAR', args: { IMG: D.IMG(), VAR: D.VAR('selection_gardee') }, pdb: ['gimp-selection-save'],
      help: 'Garde la sélection dans un canal. Pour la récupérer : « sélectionner la forme de » + la variable.', gen: function (b, c) { return c.var(b, 'VAR') + ' = pdb.gimp_selection_save(' + img(c, b) + ')\n'; } },
    { type: 'sel_empty', cat: 'sel', out: ['Boolean'], sep: 'Questions', msg: 'la sélection de %IMG est vide', args: { IMG: D.IMG() }, pdb: ['gimp-selection-is-empty'],
      help: 'Vrai si rien n\'est sélectionné.', gen: function (b, c) { return ['pdb.gimp_selection_is_empty(' + img(c, b) + ')', O.CALL]; } },
    { type: 'sel_measure', cat: 'sel', out: ['Number'], msg: '%K de la sélection de %IMG', args: { K: D.DD([['gauche (x)', 'x'], ['haut (y)', 'y'], ['largeur', 'largeur'], ['hauteur', 'hauteur'], ['droite', 'droite'], ['bas', 'bas']]), IMG: D.IMG() },
      pdb: ['gimp-selection-bounds'], help: 'Le rectangle qui entoure la sélection.', gen: function (b, c) { c.need('_mesure_selection'); return ['_mesure_selection(' + img(c, b) + ', "' + c.f(b, 'K') + '")', O.CALL]; } },
    { type: 'sel_to_path', cat: 'sel', msg: 'transformer la sélection de %IMG en chemin', args: { IMG: D.IMG() }, pdb: ['plug-in-sel2path'],
      help: 'Crée un chemin qui suit le bord de la sélection.', gen: function (b, c) { return 'pdb.plug_in_sel2path(' + img(c, b) + ', None)\n'; } },

    /* ===== couleurs & peinture ===== */
    { type: 'paint_fg', cat: 'paint', msg: 'couleur de premier plan : %C', args: { C: D.COL('#000000') }, pdb: ['gimp-context-set-foreground'],
      help: 'Choisit la couleur principale (le carré du dessus dans la boîte à outils).', gen: function (b, c) { return 'pdb.gimp_context_set_foreground(' + c.col(b, 'C') + ')\n'; } },
    { type: 'paint_bg', cat: 'paint', msg: 'couleur d\'arrière-plan : %C', args: { C: D.COL('#ffffff') }, pdb: ['gimp-context-set-background'],
      help: 'Choisit la couleur secondaire.', gen: function (b, c) { return 'pdb.gimp_context_set_background(' + c.col(b, 'C') + ')\n'; } },
    { type: 'paint_default', cat: 'paint', msg: 'couleurs par défaut (noir / blanc)', args: {}, pdb: ['gimp-context-set-default-colors'],
      help: 'Remet noir en premier plan et blanc en arrière-plan.', gen: function () { return 'pdb.gimp_context_set_default_colors()\n'; } },
    { type: 'paint_swap', cat: 'paint', msg: 'échanger premier plan et arrière-plan', args: {}, pdb: ['gimp-context-swap-colors'],
      help: 'Inverse les deux couleurs.', gen: function () { return 'pdb.gimp_context_swap_colors()\n'; } },
    { type: 'paint_fill_color', cat: 'paint', sep: 'Remplir & effacer', msg: 'remplir la sélection de %L avec la couleur %C', args: { L: D.LAY(), C: D.COL('#ffffff') },
      pdb: ['gimp-context-set-foreground', 'gimp-edit-fill'], help: 'Peint la zone sélectionnée avec cette couleur (tout le calque s\'il n\'y a pas de sélection).', kw: 'blanc bulle nettoyer',
      gen: function (b, c) { return 'pdb.gimp_context_set_foreground(' + c.col(b, 'C') + ')\npdb.gimp_edit_fill(' + c.obj(b, 'L') + ', FILL_FOREGROUND)\n'; } },
    { type: 'paint_fill_sel', cat: 'paint', msg: 'remplir la sélection de %L avec %F', args: { L: D.LAY(), F: D.DD(OP.FILL) }, pdb: ['gimp-edit-fill'],
      help: 'Remplit la zone sélectionnée (tout le calque s\'il n\'y a pas de sélection).', gen: function (b, c) { return 'pdb.gimp_edit_fill(' + c.obj(b, 'L') + ', ' + c.f(b, 'F') + ')\n'; } },
    { type: 'paint_fill_all', cat: 'paint', msg: 'remplir tout %L avec %F', args: { L: D.LAY(), F: D.DD(OP.FILL) }, pdb: ['gimp-drawable-fill'],
      help: 'Remplit le calque entier, en ignorant la sélection.', gen: function (b, c) { return 'pdb.gimp_drawable_fill(' + c.obj(b, 'L') + ', ' + c.f(b, 'F') + ')\n'; } },
    { type: 'paint_clear', cat: 'paint', msg: 'effacer la sélection dans %L', args: { L: D.LAY() }, pdb: ['gimp-edit-clear'],
      help: 'Efface le contenu sélectionné (transparent si le calque a de la transparence).', kw: 'gomme supprimer', gen: function (b, c) { return 'pdb.gimp_edit_clear(' + c.obj(b, 'L') + ')\n'; } },
    { type: 'paint_desat', cat: 'paint', sep: 'Retouches', msg: 'passer %L en noir et blanc %M', args: { L: D.LAY(), M: D.DD([['(luminance)', 'DESATURATE_LUMINANCE'], ['(luminosité)', 'DESATURATE_LUMA'], ['(clarté)', 'DESATURATE_LIGHTNESS'], ['(moyenne)', 'DESATURATE_AVERAGE'], ['(valeur)', 'DESATURATE_VALUE']]) },
      pdb: ['gimp-drawable-desaturate'], help: 'Retire les couleurs du calque (désaturer).', kw: 'gris desaturer', gen: function (b, c) { return 'pdb.gimp_drawable_desaturate(' + c.obj(b, 'L') + ', ' + c.f(b, 'M') + ')\n'; } },
    { type: 'paint_bc', cat: 'paint', msg: 'luminosité %B contraste %C de %L %BR (de -100 à 100)', args: { B: D.NUM(0), C: D.NUM(30), L: D.LAY() }, pdb: ['gimp-drawable-brightness-contrast'],
      help: 'Éclaircit/assombrit et renforce le contraste.', gen: function (b, c) { return 'pdb.gimp_drawable_brightness_contrast(' + c.obj(b, 'L') + ', ' + c.num(b, 'B', O.MUL) + ' / 100.0, ' + c.num(b, 'C', O.MUL) + ' / 100.0)\n'; } },
    { type: 'paint_invert', cat: 'paint', msg: 'inverser les couleurs de %L', args: { L: D.LAY() }, pdb: ['gimp-drawable-invert'],
      help: 'Négatif : le blanc devient noir, etc.', gen: function (b, c) { return 'pdb.gimp_drawable_invert(' + c.obj(b, 'L') + ', False)\n'; } },
    { type: 'paint_threshold', cat: 'paint', msg: 'seuil noir/blanc de %L entre %A et %B %BR (de 0 à 255)', args: { L: D.LAY(), A: D.NUM(127), B: D.NUM(255) }, pdb: ['gimp-drawable-threshold'],
      help: 'Les pixels entre les deux valeurs deviennent blancs, les autres noirs.', gen: function (b, c) { return 'pdb.gimp_drawable_threshold(' + c.obj(b, 'L') + ', HISTOGRAM_VALUE, ' + c.num(b, 'A', O.MUL) + ' / 255.0, ' + c.num(b, 'B', O.MUL) + ' / 255.0)\n'; } },
    { type: 'paint_c2a', cat: 'paint', msg: 'rendre la couleur %C transparente dans %L', args: { C: D.COL('#ffffff'), L: D.LAY() }, pdb: ['plug-in-colortoalpha'],
      help: 'Transforme une couleur en transparence (Couleurs ▸ Couleur vers alpha).', kw: 'fond transparent',
      gen: function (b, c) { var l = c.obj(b, 'L'); return 'pdb.plug_in_colortoalpha(' + imgOf(c, l) + ', ' + l + ', ' + c.col(b, 'C') + ')\n'; } },
    { type: 'paint_blur', cat: 'paint', msg: 'flou gaussien de %N px sur %L', args: { N: D.NUM(5), L: D.LAY() }, pdb: ['plug-in-gauss'],
      help: 'Rend flou le calque (ou la sélection).', gen: function (b, c) { var l = c.obj(b, 'L'), n = c.num(b, 'N'); return 'pdb.plug_in_gauss(' + imgOf(c, l) + ', ' + l + ', ' + n + ', ' + n + ', 1)\n'; } },
    { type: 'paint_shadow', cat: 'paint', msg: 'ombre portée sur %L décalage %X , %Y %BR flou %R couleur %C opacité %O', args: { L: D.LAY(), X: D.NUM(4), Y: D.NUM(4), R: D.NUM(15), C: D.COL('#000000'), O: D.NUM(60) },
      pdb: ['script-fu-drop-shadow'], help: 'Ajoute une ombre sous le contenu (ou la sélection).',
      gen: function (b, c) { var l = c.obj(b, 'L'); return 'pdb.script_fu_drop_shadow(' + imgOf(c, l) + ', ' + l + ', ' + c.num(b, 'X') + ', ' + c.num(b, 'Y') + ', ' + c.num(b, 'R') + ', ' + c.col(b, 'C') + ', ' + c.num(b, 'O') + ', True)\n'; } },
    { type: 'paint_brush', cat: 'paint', sep: 'Dessiner', msg: 'taille du pinceau : %N px', args: { N: D.NUM(10) }, pdb: ['gimp-context-set-brush-size'],
      help: 'La taille utilisée par les blocs de dessin.', gen: function (b, c) { return 'pdb.gimp_context_set_brush_size(' + c.num(b, 'N') + ')\n'; } },
    { type: 'paint_line', cat: 'paint', msg: 'tracer au pinceau sur %L de x %X1 y %Y1 à x %X2 y %Y2', args: { L: D.LAY(), X1: D.NUM(0), Y1: D.NUM(0), X2: D.NUM(100), Y2: D.NUM(100) },
      pdb: ['gimp-paintbrush-default'], help: 'Dessine un trait avec la couleur de premier plan.',
      gen: function (b, c) { return 'pdb.gimp_paintbrush_default(' + c.obj(b, 'L') + ', 4, [' + [c.num(b, 'X1'), c.num(b, 'Y1'), c.num(b, 'X2'), c.num(b, 'Y2')].join(', ') + '])\n'; } },
    { type: 'paint_stroke_sel', cat: 'paint', msg: 'tracer le contour de la sélection sur %L', args: { L: D.LAY() }, pdb: ['gimp-drawable-edit-stroke-selection'],
      help: 'Dessine le bord de la sélection avec le pinceau actuel.', gen: function (b, c) { return 'pdb.gimp_drawable_edit_stroke_selection(' + c.obj(b, 'L') + ')\n'; } },
    { type: 'paint_pixel', cat: 'paint', out: ['Colour'], sep: 'Couleurs à utiliser', msg: 'couleur du pixel x %X y %Y de %L', args: { X: D.NUM(0), Y: D.NUM(0), L: D.LAY() }, pdb: ['gimp-drawable-get-pixel'],
      help: 'La couleur exacte d\'un point du calque.', kw: 'pipette', gen: function (b, c) { c.need('_couleur_pixel'); return ['_couleur_pixel(' + c.obj(b, 'L') + ', ' + c.num(b, 'X') + ', ' + c.num(b, 'Y') + ')', O.CALL]; } },
    { type: 'paint_rgb', cat: 'paint', out: ['Colour'], msg: 'couleur rouge %R vert %G bleu %B', args: { R: D.NUM(255), G: D.NUM(0), B: D.NUM(0) },
      help: 'Fabrique une couleur à partir de trois nombres de 0 à 255.', gen: function (b, c) { return ['(' + c.int(b, 'R') + ', ' + c.int(b, 'G') + ', ' + c.int(b, 'B') + ')', O.ATOMIC]; } }
  ];
});
})(typeof window !== 'undefined' ? window : globalThis);
